### ISSUE TITLE
Colors not rendering in pager

### ISSUE THREAD

**Issue by victorlin** [nextstrain/readthedocs-cli#4]
I'm not familiar with `rich` but the colors aren't rendering in my terminal (tried `zsh` and `bash`).

### Current Behavior

Pager output of `rtd projects nextstrain`:

```
nextstrain nextstrain ESC[1m<ESC[0mESC[4;94mhttps:ESC[0mESC[4;94m//docs.nextstrain.org/en/latest/ESC[0mESC[1m>ESC[0m
(END)
```

### Expected behavior

Output should be this with pretty colors:

```
nextstrain <https://docs.nextstrain.org/en/latest/>
(END)
```

### Your environment

 - Version: [v3](https://github.com/nextstrain/readthedocs-cli/releases/tag/v3)

**Comment by tsibley** [comment]
Fixed in v4.
